// ===================================================================
// MSRA STUDY APP — core data
//   window.SPECIALTIES — clinical tracker (Clinical Problem Solving blueprint)
//   window.PHASES      — adaptive revision plan (both papers)
//   window.TIPS        — strategy tips shown on the Plan view
//   window.EXAM_DATE / window.PLAN_START — default timeline (user-overridable)
//
// Specialty IDs are kept stable forever — statuses, notes and timestamps are
// keyed off the CONDITION ids. Several specialty ids deliberately match the
// constellation shape keys in index.html (cardiology, respiratory, gastro,
// renal, endocrinology, neurology, psychiatry, rheumatology, dermatology,
// infectious, haematology, ophthalmology, pharmacology) so the skill-tree
// renders a bespoke silhouette for each.
// ===================================================================

window.SPECIALTIES = [
  {
    id: "cardiology",
    name: "Cardiovascular",
    icon: "🫀",
    conditions: [
      { id: "cvs_hypertension", name: "Hypertension", presentation: "Usually asymptomatic; found on screening. Stages by clinic and ambulatory/home readings.", investigations: "ABPM/HBPM to confirm, U&E, HbA1c, lipids, ECG, urine ACR, QRISK.", treatment: "Lifestyle; ACE-i/ARB if <55 or diabetic, CCB if ≥55 or Black African/Caribbean; add thiazide-like diuretic; target <140/90 (<135/85 home)." },
      { id: "cvs_af", name: "Atrial fibrillation", presentation: "Palpitations, breathlessness, irregularly irregular pulse; may be incidental.", investigations: "ECG (absent P waves), TFTs, U&E, echocardiogram.", treatment: "Rate control with bisoprolol or diltiazem; anticoagulate by CHA₂DS₂-VASc balanced against ORBIT/HAS-BLED; DOAC first line." },
      { id: "cvs_acs", name: "Acute coronary syndrome", presentation: "Central crushing chest pain, radiation to jaw/arm, sweating, nausea; may be silent in diabetics/elderly.", investigations: "ECG (ST changes), serial troponin.", treatment: "MONA plus dual antiplatelet; primary PCI for STEMI; risk-stratify NSTEM with GRACE." },
      { id: "cvs_angina", name: "Stable angina", presentation: "Predictable exertional chest tightness relieved by rest or GTN.", investigations: "CT coronary angiography first line, ECG, bloods, assess risk factors.", treatment: "GTN spray for attacks; beta-blocker or CCB first line; aspirin and statin; consider revascularisation." },
      { id: "cvs_heart_failure", name: "Heart failure", presentation: "Breathlessness, orthopnoea, paroxysmal nocturnal dyspnoea, oedema, raised JVP, bibasal crackles.", investigations: "NT-proBNP, echocardiogram, ECG, CXR.", treatment: "ACE-i + beta-blocker, then MRA; SGLT2 inhibitor; loop diuretic for symptoms; manage cause." },
      { id: "cvs_aortic_stenosis", name: "Aortic stenosis", presentation: "Exertional syncope, angina, dyspnoea; ejection systolic murmur radiating to carotids, slow-rising pulse.", investigations: "Echocardiogram (valve area, gradient), ECG.", treatment: "Valve replacement (surgical or TAVI) once symptomatic or severe; avoid vasodilators." },
      { id: "cvs_endocarditis", name: "Infective endocarditis", presentation: "Fever, new murmur, splinter haemorrhages, Janeway lesions, Osler nodes; risk with prosthetic valves/IVDU.", investigations: "Blood cultures (3 sets), echocardiogram; modified Duke criteria.", treatment: "Prolonged IV antibiotics; surgery for heart failure, abscess or large vegetations." },
      { id: "cvs_dvt", name: "Deep vein thrombosis", presentation: "Unilateral calf swelling, tenderness, warmth, redness.", investigations: "Two-level Wells score; D-dimer if low risk; proximal leg vein ultrasound.", treatment: "DOAC for at least 3 months; longer if unprovoked or ongoing risk; investigate for cancer if unprovoked." },
      { id: "cvs_pe", name: "Pulmonary embolism", presentation: "Pleuritic chest pain, breathlessness, haemoptysis, tachycardia, hypoxia.", investigations: "Wells score; CTPA (or V/Q); ECG (sinus tachycardia, S1Q3T3); ABG.", treatment: "DOAC; thrombolysis if massive with haemodynamic instability." },
      { id: "cvs_pad", name: "Peripheral arterial disease", presentation: "Intermittent claudication, cold pale leg, absent pulses; critical ischaemia gives rest pain and ulcers.", investigations: "Ankle-brachial pressure index, duplex ultrasound.", treatment: "Risk factor control, supervised exercise, statin and antiplatelet; angioplasty/bypass for severe disease." },
      { id: "cvs_svt", name: "Supraventricular tachycardia", presentation: "Sudden palpitations, regular narrow-complex tachycardia, sometimes chest discomfort.", investigations: "ECG during episode, TFTs, electrolytes.", treatment: "Vagal manoeuvres then IV adenosine; cardioversion if unstable; consider ablation for recurrence." },
      { id: "cvs_pericarditis", name: "Pericarditis", presentation: "Sharp pleuritic chest pain relieved by sitting forward; pericardial rub.", investigations: "ECG (saddle-shaped ST elevation, PR depression), troponin, echocardiogram.", treatment: "NSAID plus colchicine; treat underlying cause; watch for tamponade." },
      { id: "cvs_aaa", name: "Abdominal aortic aneurysm", presentation: "Often asymptomatic; pulsatile mass; rupture gives sudden abdominal/back pain and collapse.", investigations: "Abdominal ultrasound (screening offered to men at 65); CT for sizing.", treatment: "Monitor if small; elective repair at ≥5.5 cm; emergency surgery if ruptured." },
    ],
  },
  {
    id: "respiratory",
    name: "Respiratory",
    icon: "🫁",
    conditions: [
      { id: "resp_asthma", name: "Asthma", presentation: "Episodic wheeze, cough, breathlessness with diurnal and trigger variation.", investigations: "Spirometry with reversibility, FeNO, peak flow diary.", treatment: "SABA plus low-dose ICS; step up to ICS/LABA (MART); review inhaler technique and adherence." },
      { id: "resp_copd", name: "COPD", presentation: "Chronic productive cough, breathlessness, wheeze in a smoker over 35.", investigations: "Post-bronchodilator spirometry (FEV1/FVC <0.7), CXR, BMI, FBC.", treatment: "Stop smoking, vaccinate, pulmonary rehab; SABA/SAMA, then LABA/LAMA; add ICS if asthmatic features." },
      { id: "resp_cap", name: "Community-acquired pneumonia", presentation: "Fever, productive cough, pleuritic pain, focal crackles, bronchial breathing.", investigations: "CXR, CRP, U&E, CURB-65, sputum/blood cultures if severe.", treatment: "Amoxicillin for low severity; add macrolide or use co-amoxiclav for higher CURB-65; admit if score high." },
      { id: "resp_lung_cancer", name: "Lung cancer", presentation: "Haemoptysis, weight loss, persistent cough, finger clubbing; may cause SVC obstruction or hoarseness.", investigations: "Urgent CXR then contrast CT, biopsy/bronchoscopy, PET for staging.", treatment: "Surgery, radiotherapy, chemo or immunotherapy by type and stage; refer on 2-week-wait." },
      { id: "resp_pneumothorax", name: "Pneumothorax", presentation: "Sudden pleuritic chest pain and breathlessness; tension gives tracheal deviation and shock.", investigations: "CXR (avoid in suspected tension — treat clinically).", treatment: "Tension: immediate large-bore decompression. Otherwise observe, aspirate, or chest drain by size/symptoms." },
      { id: "resp_effusion", name: "Pleural effusion", presentation: "Breathlessness, reduced expansion, stony dull percussion, reduced breath sounds.", investigations: "CXR, pleural ultrasound, diagnostic aspiration with Light's criteria.", treatment: "Treat cause; drain if symptomatic; transudate vs exudate guides workup." },
      { id: "resp_bronchiectasis", name: "Bronchiectasis", presentation: "Chronic cough with copious purulent sputum, recurrent infections, coarse crackles.", investigations: "High-resolution CT, sputum culture, immunoglobulins, CF screen if young.", treatment: "Airway clearance physiotherapy, treat exacerbations promptly, manage cause." },
      { id: "resp_osa", name: "Obstructive sleep apnoea", presentation: "Snoring, witnessed apnoeas, daytime sleepiness, morning headache; often obese.", investigations: "Epworth score, polysomnography/oximetry.", treatment: "Weight loss, avoid alcohol, CPAP; advise DVLA and driving rules." },
      { id: "resp_tb", name: "Tuberculosis", presentation: "Chronic cough, weight loss, night sweats, haemoptysis; risk with immunosuppression/travel.", investigations: "CXR, sputum smear and culture, NAAT; interferon-gamma release assay for latent TB.", treatment: "RIPE for 2 months then rifampicin and isoniazid for 4; notify; directly observed therapy if needed." },
      { id: "resp_uri", name: "Upper respiratory tract infection", presentation: "Coryza, sore throat, cough, low-grade fever; usually self-limiting and viral.", investigations: "Clinical; FeverPAIN/Centor for sore throat.", treatment: "Reassure, safety-net, symptomatic care; antibiotics only when bacterial features." },
    ],
  },
  {
    id: "gastro",
    name: "Gastroenterology & Nutrition",
    icon: "🩻",
    conditions: [
      { id: "gi_gord", name: "GORD", presentation: "Retrosternal burning, acid regurgitation, worse lying down or after meals.", investigations: "Clinical; endoscopy if alarm features (dysphagia, weight loss, anaemia, age >55 persistent).", treatment: "Lifestyle, weight loss, PPI; test/treat H. pylori; fundoplication for refractory cases." },
      { id: "gi_pud", name: "Peptic ulcer disease", presentation: "Epigastric pain (duodenal eased by food, gastric worse with food), may bleed.", investigations: "H. pylori testing, endoscopy, FBC.", treatment: "PPI; eradicate H. pylori; stop NSAIDs; endoscopic therapy for bleeding." },
      { id: "gi_coeliac", name: "Coeliac disease", presentation: "Diarrhoea, bloating, weight loss, fatigue, iron/folate deficiency, dermatitis herpetiformis.", investigations: "Anti-tTG IgG with total IgA while on gluten; duodenal biopsy confirms.", treatment: "Lifelong gluten-free diet; replace deficiencies; pneumococcal vaccination." },
      { id: "gi_ibs", name: "Irritable bowel syndrome", presentation: "Abdominal pain relieved by defaecation, bloating, altered bowel habit without alarm features.", investigations: "Exclude organic disease: FBC, CRP, coeliac serology, faecal calprotectin.", treatment: "Diet (low FODMAP), antispasmodics, laxatives/loperamide, low-dose tricyclic, reassurance." },
      { id: "gi_crohns", name: "Crohn's disease", presentation: "Crampy pain, non-bloody diarrhoea, weight loss, mouth ulcers, perianal disease; any part of gut.", investigations: "Faecal calprotectin, colonoscopy with biopsy, MRI for fistulae.", treatment: "Induce with steroids; maintain with azathioprine or biologics; stop smoking; surgery for complications." },
      { id: "gi_uc", name: "Ulcerative colitis", presentation: "Bloody diarrhoea, urgency, tenesmus, lower abdominal pain; continuous from rectum.", investigations: "Faecal calprotectin, colonoscopy, stool culture to exclude infection.", treatment: "Aminosalicylates for mild; steroids for flares; biologics; colectomy is curative." },
      { id: "gi_gallstones", name: "Gallstones & biliary colic", presentation: "Right upper quadrant pain after fatty food; fever and jaundice suggest cholangitis/cholecystitis.", investigations: "Abdominal ultrasound, LFTs, amylase; MRCP for duct stones.", treatment: "Analgesia, laparoscopic cholecystectomy; ERCP for ductal stones; antibiotics for infection." },
      { id: "gi_pancreatitis", name: "Acute pancreatitis", presentation: "Severe epigastric pain radiating to the back, vomiting; gallstones and alcohol are commonest.", investigations: "Amylase/lipase, U&E, calcium, glucose, LFTs; CT; Glasgow score.", treatment: "IV fluids, analgesia, oxygen, treat cause; manage in HDU if severe." },
      { id: "gi_cirrhosis", name: "Liver cirrhosis", presentation: "Jaundice, ascites, spider naevi, encephalopathy, variceal bleeding.", investigations: "LFTs, clotting, albumin, ultrasound, fibroscan, ascitic tap.", treatment: "Treat cause, alcohol abstinence; manage complications; surveillance for HCC; transplant assessment." },
      { id: "gi_hepatitis", name: "Viral hepatitis", presentation: "Malaise, jaundice, RUQ discomfort, deranged LFTs; risk factors guide type.", investigations: "Hepatitis A/B/C serology, LFTs, clotting.", treatment: "Supportive for A; antivirals for chronic B/C; notify; vaccinate contacts for B." },
      { id: "gi_colorectal_ca", name: "Colorectal cancer", presentation: "Change in bowel habit, rectal bleeding, weight loss, iron-deficiency anaemia, tenesmus.", investigations: "FIT testing, colonoscopy with biopsy, CT for staging, CEA.", treatment: "Surgical resection, chemo/radiotherapy; refer on 2-week-wait; participate in screening." },
      { id: "gi_diverticular", name: "Diverticular disease", presentation: "Left lower quadrant pain, altered bowel habit; diverticulitis adds fever and tenderness.", investigations: "CT abdomen for acute episodes, colonoscopy when settled.", treatment: "High-fibre diet; antibiotics and analgesia for diverticulitis; surgery for complications." },
      { id: "gi_b12_folate", name: "B12 & folate deficiency", presentation: "Fatigue, glossitis, macrocytic anaemia; B12 deficiency adds neurological signs.", investigations: "FBC and blood film, B12, folate, intrinsic factor antibodies.", treatment: "Replace B12 (IM hydroxocobalamin) before folate to avoid cord degeneration; treat cause." },
    ],
  },
  {
    id: "endocrinology",
    name: "Endocrinology & Metabolic",
    icon: "🧬",
    conditions: [
      { id: "endo_t1dm", name: "Type 1 diabetes", presentation: "Young patient with polyuria, polydipsia, weight loss, may present in DKA.", investigations: "Glucose, ketones, HbA1c, autoantibodies, C-peptide.", treatment: "Basal-bolus insulin, carbohydrate counting, structured education, screen for complications." },
      { id: "endo_t2dm", name: "Type 2 diabetes", presentation: "Often asymptomatic; thirst, fatigue, recurrent infections, found on screening.", investigations: "HbA1c (≥48 mmol/mol), fasting glucose; annual retinal, foot and renal checks.", treatment: "Lifestyle then metformin; add SGLT2 inhibitor/GLP-1 with cardiovascular or renal disease; individualise targets." },
      { id: "endo_dka", name: "Diabetic ketoacidosis", presentation: "Vomiting, abdominal pain, Kussmaul breathing, ketotic breath, dehydration, drowsiness.", investigations: "Capillary/blood ketones, glucose, venous gas, U&E.", treatment: "IV fluids, fixed-rate insulin, potassium replacement, monitor closely; treat trigger." },
      { id: "endo_hypothyroid", name: "Hypothyroidism", presentation: "Fatigue, weight gain, cold intolerance, constipation, dry skin, bradycardia.", investigations: "TSH (high) and free T4 (low); thyroid peroxidase antibodies.", treatment: "Levothyroxine titrated to TSH; start low in elderly/cardiac patients." },
      { id: "endo_hyperthyroid", name: "Hyperthyroidism", presentation: "Weight loss, heat intolerance, tremor, palpitations; Graves adds eye signs and goitre.", investigations: "TSH (low), free T4/T3 (high), TSH-receptor antibodies, isotope scan.", treatment: "Beta-blocker for symptoms; carbimazole; radioiodine or surgery; treat thyroid storm urgently." },
      { id: "endo_hyperlipidaemia", name: "Hyperlipidaemia", presentation: "Asymptomatic; xanthelasma, tendon xanthomata, corneal arcus in familial disease.", investigations: "Lipid profile, QRISK3, exclude secondary causes.", treatment: "Lifestyle; atorvastatin for primary prevention if QRISK ≥10% and all secondary prevention." },
      { id: "endo_addisons", name: "Addison's disease", presentation: "Fatigue, weight loss, hyperpigmentation, postural hypotension; crisis gives shock.", investigations: "Short Synacthen test, 9am cortisol, U&E (low Na, high K), adrenal antibodies.", treatment: "Hydrocortisone and fludrocortisone; sick-day rules; emergency IV steroids for crisis." },
      { id: "endo_cushings", name: "Cushing's syndrome", presentation: "Central obesity, moon face, striae, proximal myopathy, easy bruising, hypertension.", investigations: "Overnight dexamethasone suppression, 24h urinary cortisol, late-night salivary cortisol; ACTH.", treatment: "Treat cause (stop steroids, remove tumour); manage hypertension and glucose." },
      { id: "endo_hyperparathyroid", name: "Hyperparathyroidism", presentation: "Bones, stones, abdominal moans and psychic groans of hypercalcaemia; often incidental.", investigations: "Calcium (high), PTH (high or inappropriately normal), phosphate, vitamin D, renal imaging.", treatment: "Hydration; parathyroidectomy for symptomatic or significant primary disease." },
      { id: "endo_hyperkalaemia", name: "Hyperkalaemia", presentation: "Often asymptomatic; weakness, palpitations; ECG changes risk arrhythmia.", investigations: "U&E, venous gas, ECG (tall T waves, wide QRS), review drugs.", treatment: "IV calcium gluconate to protect heart, insulin-dextrose and salbutamol to shift; treat cause." },
      { id: "endo_hyponatraemia", name: "Hyponatraemia", presentation: "Nausea, confusion, seizures when severe; assess fluid status.", investigations: "Serum and urine osmolality, urine sodium, TFTs, cortisol; classify by volume status.", treatment: "Treat cause; fluid restrict in SIADH; cautious correction to avoid osmotic demyelination." },
      { id: "endo_obesity", name: "Obesity", presentation: "Raised BMI with associated metabolic, joint and psychological complications.", investigations: "BMI, waist circumference, HbA1c, lipids, blood pressure, liver screen.", treatment: "Diet, activity, behavioural support; orlistat; GLP-1 agonists; bariatric surgery in selected patients." },
    ],
  },
  {
    id: "renal",
    name: "Renal & Urology",
    icon: "🫘",
    conditions: [
      { id: "renal_aki", name: "Acute kidney injury", presentation: "Reduced urine output, rising creatinine; oliguria, fluid overload or uraemia.", investigations: "U&E, urinalysis, fluid assessment, ultrasound, review nephrotoxic drugs.", treatment: "Treat cause, optimise fluids, stop nephrotoxics; dialysis for refractory hyperkalaemia, acidosis or overload." },
      { id: "renal_ckd", name: "Chronic kidney disease", presentation: "Often asymptomatic; fatigue, oedema, anaemia, bone disease in advanced disease.", investigations: "eGFR and ACR over time, U&E, renal ultrasound, urinalysis.", treatment: "Control BP with ACE-i/ARB, SGLT2 inhibitor, treat anaemia/bone disease; plan dialysis/transplant if progressive." },
      { id: "renal_uti", name: "Urinary tract infection", presentation: "Dysuria, frequency, urgency, suprapubic pain; pyelonephritis adds fever and loin pain.", investigations: "Urine dipstick, MSU culture; imaging for recurrent/atypical disease.", treatment: "Nitrofurantoin or trimethoprim for simple cystitis; longer course and broader cover for pyelonephritis." },
      { id: "renal_nephrotic", name: "Nephrotic syndrome", presentation: "Heavy proteinuria, oedema, hypoalbuminaemia, hyperlipidaemia.", investigations: "Urine ACR/PCR, albumin, lipids, renal biopsy, autoimmune screen.", treatment: "Treat cause, steroids (e.g. minimal change), ACE-i/ARB, manage oedema and thrombosis risk." },
      { id: "renal_stones", name: "Renal & ureteric stones", presentation: "Severe loin-to-groin colic, haematuria, vomiting, restlessness.", investigations: "Non-contrast CT KUB, urinalysis, U&E, calcium, urate.", treatment: "Analgesia (NSAID), fluids; medical expulsive therapy; lithotripsy/ureteroscopy; urgent decompression if infected and obstructed." },
      { id: "renal_bph", name: "Benign prostatic hyperplasia", presentation: "Hesitancy, weak stream, nocturia, incomplete emptying in older men.", investigations: "IPSS, examination, PSA after counselling, urinalysis, flow studies.", treatment: "Alpha-blocker (tamsulosin); 5-alpha-reductase inhibitor for large glands; TURP for refractory cases." },
      { id: "renal_haematuria", name: "Haematuria", presentation: "Visible or non-visible blood in urine; painless visible haematuria is cancer until excluded.", investigations: "Urinalysis, cytology, cystoscopy, CT urogram, U&E.", treatment: "2-week-wait referral for visible haematuria over 45; treat identified cause." },
      { id: "renal_prostate_ca", name: "Prostate cancer", presentation: "Often asymptomatic; lower urinary tract symptoms, bone pain in advanced disease.", investigations: "PSA, multiparametric MRI, transrectal biopsy, bone scan; Gleason grading.", treatment: "Active surveillance, radical prostatectomy, radiotherapy, hormone therapy by risk and stage." },
      { id: "renal_torsion", name: "Testicular torsion", presentation: "Sudden severe testicular pain, swelling, high-riding testis, absent cremasteric reflex; teenagers.", investigations: "Clinical diagnosis — do not delay; Doppler only if it will not cause delay.", treatment: "Emergency surgical exploration and bilateral fixation within 6 hours." },
      { id: "renal_incontinence", name: "Urinary incontinence", presentation: "Stress leakage on coughing, urge with urgency, or mixed; impacts quality of life.", investigations: "Bladder diary, urinalysis, post-void residual, urodynamics if unclear.", treatment: "Pelvic floor exercises and bladder training; antimuscarinics/mirabegron for urge; surgery for stress." },
      { id: "renal_epididymo", name: "Epididymo-orchitis", presentation: "Gradual unilateral testicular pain and swelling, dysuria, fever; relieved by elevation.", investigations: "Urinalysis, STI screen if young, ultrasound to exclude torsion/abscess.", treatment: "Antibiotics targeting likely organism (STI vs enteric), analgesia, scrotal support." },
    ],
  },
  {
    id: "neurology",
    name: "Neurology",
    icon: "🧠",
    conditions: [
      { id: "neuro_migraine", name: "Migraine", presentation: "Unilateral throbbing headache with nausea, photophobia, phonophobia, sometimes aura.", investigations: "Clinical; exclude red flags; headache diary.", treatment: "Triptan plus NSAID for attacks; propranolol or topiramate for prophylaxis; avoid medication overuse." },
      { id: "neuro_tension", name: "Tension-type headache", presentation: "Bilateral tight band-like pressure, no nausea, not aggravated by activity.", investigations: "Clinical diagnosis.", treatment: "Reassurance, simple analgesia, stress and posture management; avoid overuse." },
      { id: "neuro_cluster", name: "Cluster headache", presentation: "Severe unilateral periorbital pain in clusters with lacrimation, ptosis, nasal congestion.", investigations: "Clinical; MRI to exclude secondary causes.", treatment: "High-flow oxygen and subcutaneous sumatriptan for attacks; verapamil for prevention." },
      { id: "neuro_stroke", name: "Stroke & TIA", presentation: "Sudden focal deficit: weakness, speech disturbance, visual loss, facial droop.", investigations: "Urgent CT head to exclude bleed, ECG, carotid imaging, glucose.", treatment: "Thrombolysis/thrombectomy for ischaemic stroke in window; aspirin then clopidogrel; TIA needs urgent assessment." },
      { id: "neuro_epilepsy", name: "Epilepsy & seizures", presentation: "Recurrent seizures, focal or generalised; tongue-biting, incontinence, post-ictal confusion.", investigations: "EEG, MRI brain, ECG, bloods; first seizure clinic referral.", treatment: "Lamotrigine/levetiracetam for focal; sodium valproate avoided in those who can become pregnant; advise on driving and safety." },
      { id: "neuro_parkinsons", name: "Parkinson's disease", presentation: "Resting tremor, bradykinesia, rigidity, postural instability, hypomimia.", investigations: "Clinical diagnosis; DaTscan if uncertain.", treatment: "Levodopa with a dopa-decarboxylase inhibitor; dopamine agonists; MDT support; do not abruptly stop medication." },
      { id: "neuro_ms", name: "Multiple sclerosis", presentation: "Relapsing neurological symptoms separated in time and space: optic neuritis, sensory, motor, bladder.", investigations: "MRI brain and cord, lumbar puncture (oligoclonal bands), visual evoked potentials.", treatment: "Steroids for relapses; disease-modifying therapy; symptom control and MDT input." },
      { id: "neuro_bells", name: "Bell's palsy", presentation: "Sudden unilateral lower motor neurone facial weakness including forehead.", investigations: "Clinical; consider causes if atypical (Lyme, zoster).", treatment: "Prednisolone within 72 hours; eye protection with lubricants and taping at night." },
      { id: "neuro_gca", name: "Giant cell arteritis", presentation: "New temporal headache, jaw claudication, scalp tenderness, visual loss in over-50s.", investigations: "ESR/CRP raised, temporal artery biopsy/ultrasound.", treatment: "Immediate high-dose steroids before biopsy to protect sight; refer urgently." },
      { id: "neuro_sah", name: "Subarachnoid haemorrhage", presentation: "Sudden thunderclap occipital headache, neck stiffness, photophobia, reduced consciousness.", investigations: "Urgent CT head; lumbar puncture for xanthochromia if CT negative after 12h.", treatment: "Neurosurgical referral, nimodipine, coiling/clipping of aneurysm." },
      { id: "neuro_carpal", name: "Carpal tunnel syndrome", presentation: "Tingling and pain in the thumb, index and middle fingers, worse at night.", investigations: "Tinel/Phalen tests, nerve conduction studies.", treatment: "Wrist splints, corticosteroid injection, surgical decompression for severe disease." },
      { id: "neuro_dementia", name: "Dementia", presentation: "Progressive memory and cognitive decline affecting function; Alzheimer's commonest.", investigations: "Cognitive testing, bloods to exclude reversible causes, brain imaging.", treatment: "Cholinesterase inhibitors for Alzheimer's, structured support, advance care planning, manage risk." },
    ],
  },
  {
    id: "psychiatry",
    name: "Psychiatry & Mental Health",
    icon: "🧩",
    conditions: [
      { id: "psych_depression", name: "Depression", presentation: "Low mood, anhedonia, low energy with sleep, appetite and concentration change for over two weeks.", investigations: "PHQ-9, risk assessment, exclude organic causes (TFTs, FBC).", treatment: "Guided self-help/CBT for mild; SSRI plus therapy for moderate-severe; safety-net and follow up early." },
      { id: "psych_gad", name: "Generalised anxiety disorder", presentation: "Excessive uncontrollable worry with restlessness, fatigue, poor concentration, muscle tension.", investigations: "GAD-7, exclude hyperthyroidism and substance use.", treatment: "Stepped care: psychoeducation, CBT, SSRI; avoid long-term benzodiazepines." },
      { id: "psych_panic", name: "Panic disorder", presentation: "Recurrent unexpected panic attacks with palpitations, breathlessness, fear of dying.", investigations: "Clinical; exclude cardiac and endocrine causes.", treatment: "CBT first line; SSRI; breathing techniques; reduce caffeine." },
      { id: "psych_bipolar", name: "Bipolar affective disorder", presentation: "Episodes of mania (elevated mood, grandiosity, reduced sleep) alternating with depression.", investigations: "Mood history, collateral, risk assessment, exclude organic/drug causes.", treatment: "Mood stabiliser (lithium) or antipsychotic; specialist care; monitor lithium levels and avoid antidepressant monotherapy." },
      { id: "psych_schizophrenia", name: "Schizophrenia", presentation: "Delusions, hallucinations, thought disorder (positive) and apathy, blunted affect (negative).", investigations: "Mental state exam, risk assessment, exclude substances and organic causes.", treatment: "Antipsychotics, psychological therapy, early intervention service; monitor metabolic side effects." },
      { id: "psych_ocd", name: "Obsessive-compulsive disorder", presentation: "Intrusive obsessional thoughts driving compulsive rituals that impair function.", investigations: "Clinical; assess severity and impact.", treatment: "CBT with exposure and response prevention; SSRI (often higher dose)." },
      { id: "psych_ptsd", name: "Post-traumatic stress disorder", presentation: "Re-experiencing, avoidance, hyperarousal and negative mood after trauma.", investigations: "Clinical history, screening tools.", treatment: "Trauma-focused CBT or EMDR; SSRI/venlafaxine if therapy declined or insufficient." },
      { id: "psych_eating", name: "Eating disorders", presentation: "Restriction, low weight, body image disturbance (anorexia) or binge-purge cycles (bulimia).", investigations: "BMI, U&E, ECG, bone density; SCOFF screen; assess medical risk.", treatment: "Specialist eating disorder service, psychological therapy, careful refeeding to avoid refeeding syndrome." },
      { id: "psych_alcohol", name: "Alcohol dependence", presentation: "Craving, tolerance, withdrawal, loss of control; withdrawal risks seizures and delirium tremens.", investigations: "AUDIT, LFTs, GGT, MCV; assess withdrawal with CIWA.", treatment: "Chlordiazepoxide-assisted withdrawal with thiamine; brief interventions, relapse-prevention support." },
      { id: "psych_risk", name: "Self-harm & suicide risk", presentation: "Thoughts, plans or acts of self-harm; assess intent, means and protective factors.", investigations: "Full risk assessment, collateral, capacity assessment.", treatment: "Ensure safety, treat injuries, mental health referral; psychosocial assessment for every presentation." },
      { id: "psych_adhd", name: "ADHD", presentation: "Persistent inattention, hyperactivity and impulsivity across settings since childhood.", investigations: "Structured assessment, collateral from school/home, rule out differentials.", treatment: "Behavioural strategies; stimulants (methylphenidate) under specialist care; monitor growth and cardiovascular status." },
      { id: "psych_postnatal", name: "Postnatal depression", presentation: "Persistent low mood, tearfulness, guilt within a year of birth; distinct from transient baby blues.", investigations: "Edinburgh Postnatal Depression Scale, risk assessment including to infant.", treatment: "Psychological therapy; SSRI considering breastfeeding; health visitor and perinatal mental health support." },
    ],
  },
  {
    id: "rheumatology",
    name: "MSK & Rheumatology",
    icon: "🦴",
    conditions: [
      { id: "rheum_oa", name: "Osteoarthritis", presentation: "Activity-related joint pain, short morning stiffness, bony swelling, reduced range.", investigations: "Clinical; X-ray shows loss of joint space, osteophytes, sclerosis, cysts.", treatment: "Exercise, weight loss, topical/oral NSAIDs, paracetamol; joint replacement for severe disease." },
      { id: "rheum_ra", name: "Rheumatoid arthritis", presentation: "Symmetrical small-joint pain and prolonged morning stiffness, swelling, fatigue.", investigations: "Rheumatoid factor, anti-CCP, ESR/CRP, X-rays, ultrasound.", treatment: "Early DMARD (methotrexate), steroid bridge, biologics; refer to rheumatology promptly." },
      { id: "rheum_gout", name: "Gout", presentation: "Acute hot, red, exquisitely tender joint, often first MTP; tophi in chronic disease.", investigations: "Joint aspiration (negatively birefringent crystals), urate (after attack), renal function.", treatment: "NSAID, colchicine or steroid for attack; allopurinol urate-lowering after, with cover." },
      { id: "rheum_osteoporosis", name: "Osteoporosis", presentation: "Asymptomatic until fragility fracture (wrist, hip, vertebra).", investigations: "FRAX, DEXA scan, calcium, vitamin D, exclude secondary causes.", treatment: "Calcium and vitamin D, bisphosphonates; lifestyle and falls prevention." },
      { id: "rheum_sle", name: "Systemic lupus erythematosus", presentation: "Fatigue, arthralgia, malar rash, photosensitivity, multi-system involvement.", investigations: "ANA, anti-dsDNA, complement, urinalysis for nephritis, FBC.", treatment: "Hydroxychloroquine, steroids and immunosuppression for flares; sun protection; monitor organs." },
      { id: "rheum_pmr", name: "Polymyalgia rheumatica", presentation: "Bilateral shoulder and hip girdle pain and stiffness in over-50s, marked morning stiffness.", investigations: "ESR/CRP raised, exclude mimics; consider coexisting giant cell arteritis.", treatment: "Low-dose prednisolone with rapid response; slow taper; bone protection." },
      { id: "rheum_as", name: "Ankylosing spondylitis", presentation: "Inflammatory back pain in young adults, worse at night, improves with exercise, reduced spinal mobility.", investigations: "MRI sacroiliac joints, X-ray, HLA-B27, ESR/CRP.", treatment: "Physiotherapy and NSAIDs; anti-TNF/IL-17 biologics for active disease." },
      { id: "rheum_fibromyalgia", name: "Fibromyalgia", presentation: "Chronic widespread pain, fatigue, unrefreshing sleep, cognitive fog with normal investigations.", investigations: "Clinical; minimal bloods to exclude alternatives.", treatment: "Education, graded exercise, CBT; amitriptyline or duloxetine; avoid opioids." },
      { id: "rheum_back_pain", name: "Mechanical low back pain", presentation: "Activity-related back pain without red flags; usually self-limiting.", investigations: "Clinical; assess red and yellow flags; imaging only if indicated.", treatment: "Keep active, analgesia, physiotherapy; address psychosocial factors; safety-net for red flags." },
      { id: "rheum_septic", name: "Septic arthritis", presentation: "Acutely hot, swollen, painful joint with fever and inability to weight-bear.", investigations: "Urgent joint aspiration for microscopy and culture, blood cultures, inflammatory markers.", treatment: "Joint washout and prolonged IV antibiotics; orthopaedic emergency." },
      { id: "rheum_psoriatic", name: "Psoriatic arthritis", presentation: "Joint pain with psoriasis, dactylitis, nail pitting; varied patterns including spinal.", investigations: "Clinical, X-rays (pencil-in-cup), inflammatory markers, skin assessment.", treatment: "NSAIDs, DMARDs, biologics; coordinate skin and joint care." },
    ],
  },
  {
    id: "dermatology",
    name: "Dermatology",
    icon: "🧴",
    conditions: [
      { id: "derm_eczema", name: "Atopic eczema", presentation: "Itchy, dry, erythematous flexural rash; relapsing; often atopic history.", investigations: "Clinical; swab if infected.", treatment: "Emollients liberally, topical steroids by potency, treat infection, avoid triggers." },
      { id: "derm_psoriasis", name: "Psoriasis", presentation: "Well-demarcated scaly erythematous plaques on extensor surfaces and scalp; nail changes.", investigations: "Clinical; assess severity and joint involvement.", treatment: "Emollients, topical steroid plus vitamin D analogue; phototherapy; systemic/biologic for severe disease." },
      { id: "derm_acne", name: "Acne vulgaris", presentation: "Comedones, papules, pustules and nodules on face, chest and back; scarring.", investigations: "Clinical; consider hormonal assessment if features.", treatment: "Topical retinoid plus benzoyl peroxide/antibiotic; oral antibiotics or COCP; isotretinoin for severe disease." },
      { id: "derm_cellulitis", name: "Cellulitis", presentation: "Spreading hot, red, tender, swollen skin with poorly defined edge, often the lower leg.", investigations: "Clinical; mark border; bloods/cultures if systemically unwell.", treatment: "Flucloxacillin first line; elevate limb; admit for IV antibiotics if severe." },
      { id: "derm_impetigo", name: "Impetigo", presentation: "Golden-crusted superficial lesions, contagious, common in children.", investigations: "Clinical; swab if extensive or recurrent.", treatment: "Topical hydrogen peroxide or fusidic acid; oral flucloxacillin if widespread; hygiene and exclusion advice." },
      { id: "derm_melanoma", name: "Melanoma", presentation: "Changing pigmented lesion: asymmetry, irregular border, colour variation, diameter, evolution.", investigations: "Dermoscopy, urgent excision biopsy with Breslow thickness.", treatment: "Wide local excision; sentinel node and oncology for advanced disease; 2-week-wait referral." },
      { id: "derm_bcc", name: "Basal cell carcinoma", presentation: "Slow-growing pearly nodule with telangiectasia, may ulcerate; sun-exposed skin.", investigations: "Clinical, dermoscopy, biopsy.", treatment: "Excision; topical/curettage for low-risk; rarely metastasises." },
      { id: "derm_scc", name: "Squamous cell carcinoma", presentation: "Rapidly growing keratotic or ulcerated nodule on sun-exposed skin; can metastasise.", investigations: "Biopsy; assess nodes.", treatment: "Surgical excision; radiotherapy; urgent referral." },
      { id: "derm_urticaria", name: "Urticaria", presentation: "Transient itchy wheals; angioedema may accompany; often allergic or idiopathic.", investigations: "Clinical; identify triggers; investigate if chronic.", treatment: "Non-sedating antihistamines; avoid triggers; adrenaline for anaphylaxis." },
      { id: "derm_shingles", name: "Shingles (herpes zoster)", presentation: "Painful dermatomal vesicular rash not crossing the midline; prodromal pain.", investigations: "Clinical; consider ophthalmic involvement.", treatment: "Oral antiviral within 72 hours, analgesia; manage post-herpetic neuralgia; ophthalmology if eye involved." },
      { id: "derm_fungal", name: "Fungal skin infections", presentation: "Itchy annular scaly rash (tinea), or macerated interdigital/intertriginous areas.", investigations: "Clinical; skin scrapings for microscopy and culture.", treatment: "Topical antifungal; oral terbinafine for nail or scalp infection." },
      { id: "derm_leg_ulcer", name: "Venous leg ulcers", presentation: "Shallow ulcer over the gaiter area with haemosiderin staining and oedema.", investigations: "ABPI before compression, wound assessment.", treatment: "Compression bandaging if arterial supply adequate, emollients, treat infection, elevate." },
    ],
  },
  {
    id: "ent",
    name: "ENT",
    icon: "👂",
    conditions: [
      { id: "ent_om", name: "Acute otitis media", presentation: "Ear pain, fever, reduced hearing in a child; bulging red tympanic membrane.", investigations: "Otoscopy.", treatment: "Usually self-limiting analgesia; delayed or immediate amoxicillin if severe, bilateral in young, or perforation." },
      { id: "ent_oe", name: "Otitis externa", presentation: "Itchy painful ear with discharge; tender tragus; canal swelling.", investigations: "Otoscopy; swab if resistant.", treatment: "Aural toilet, topical antibiotic/steroid drops; keep ear dry; consider fungal cause." },
      { id: "ent_tonsillitis", name: "Tonsillitis", presentation: "Sore throat, fever, dysphagia, tonsillar exudate, tender cervical nodes.", investigations: "FeverPAIN or Centor score.", treatment: "Analgesia; phenoxymethylpenicillin if high score; avoid amoxicillin if glandular fever possible." },
      { id: "ent_sinusitis", name: "Sinusitis", presentation: "Facial pain/pressure, nasal congestion, purulent discharge, reduced smell.", investigations: "Clinical; imaging only for complications.", treatment: "Usually viral and self-limiting; intranasal steroid; antibiotics only if severe or prolonged." },
      { id: "ent_rhinitis", name: "Allergic rhinitis", presentation: "Sneezing, itch, nasal congestion and watery rhinorrhoea, often with conjunctivitis.", investigations: "Clinical; allergy testing if needed.", treatment: "Allergen avoidance, antihistamines, intranasal steroids." },
      { id: "ent_epistaxis", name: "Epistaxis", presentation: "Nosebleed, usually anterior from Little's area; posterior bleeds are heavier.", investigations: "Assess for bleeding disorders/anticoagulants if recurrent.", treatment: "First aid pinch and lean forward; cautery or packing; treat cause." },
      { id: "ent_bppv", name: "Benign paroxysmal positional vertigo", presentation: "Brief rotational vertigo triggered by head movement, no hearing loss.", investigations: "Dix-Hallpike manoeuvre.", treatment: "Epley manoeuvre; reassurance; usually self-limiting." },
      { id: "ent_menieres", name: "Ménière's disease", presentation: "Episodic vertigo, fluctuating sensorineural hearing loss, tinnitus and aural fullness.", investigations: "Audiometry; ENT referral.", treatment: "Acute prochlorperazine; betahistine and low-salt diet for prevention; DVLA advice." },
      { id: "ent_hearing_loss", name: "Hearing loss", presentation: "Conductive (wax, effusion) or sensorineural (presbycusis, noise); sudden loss is a red flag.", investigations: "Otoscopy, tuning fork tests, audiometry.", treatment: "Treat cause; urgent ENT for sudden sensorineural loss; hearing aids for presbycusis." },
      { id: "ent_glandular", name: "Glandular fever", presentation: "Sore throat, fatigue, fever, lymphadenopathy, splenomegaly in young adults.", investigations: "Monospot/EBV serology, FBC (atypical lymphocytes), LFTs.", treatment: "Supportive; avoid contact sport for splenic rupture risk; avoid amoxicillin (rash)." },
    ],
  },
  {
    id: "ophthalmology",
    name: "Ophthalmology",
    icon: "👁️",
    conditions: [
      { id: "eye_conjunctivitis", name: "Conjunctivitis", presentation: "Red gritty eye with discharge; bilateral itch suggests allergy, purulent suggests bacterial.", investigations: "Clinical; swab if severe/neonatal.", treatment: "Bacterial often self-limiting or chloramphenicol; antihistamine for allergic; hygiene advice." },
      { id: "eye_acute_glaucoma", name: "Acute angle-closure glaucoma", presentation: "Sudden painful red eye, haloes, reduced vision, fixed mid-dilated pupil, hard eye, vomiting.", investigations: "Intraocular pressure, urgent ophthalmology assessment.", treatment: "Emergency: lower pressure (acetazolamide, pilocarpine, beta-blocker) then laser iridotomy." },
      { id: "eye_chronic_glaucoma", name: "Chronic open-angle glaucoma", presentation: "Insidious peripheral visual field loss, often asymptomatic until advanced.", investigations: "Tonometry, fundoscopy (cupping), visual fields, OCT.", treatment: "Prostaglandin analogue drops; laser or surgery; lifelong monitoring." },
      { id: "eye_cataract", name: "Cataracts", presentation: "Gradual painless blurring, glare, reduced colour, loss of red reflex.", investigations: "Slit-lamp examination, visual acuity.", treatment: "Phacoemulsification with intraocular lens when symptoms affect life." },
      { id: "eye_amd", name: "Age-related macular degeneration", presentation: "Central vision loss and distortion; dry (gradual) or wet (rapid with metamorphopsia).", investigations: "Amsler grid, OCT, fundoscopy (drusen).", treatment: "Anti-VEGF injections for wet AMD; supplements and lifestyle for dry; urgent referral for wet." },
      { id: "eye_diabetic_retino", name: "Diabetic retinopathy", presentation: "Often asymptomatic; microaneurysms, haemorrhages, exudates; neovascularisation in proliferative disease.", investigations: "Retinal screening photography, OCT.", treatment: "Optimise glucose and BP; laser photocoagulation, anti-VEGF for maculopathy/proliferative disease." },
      { id: "eye_retinal_detach", name: "Retinal detachment", presentation: "Sudden floaters, flashes and a curtain over the vision; painless.", investigations: "Urgent fundoscopy/ophthalmology.", treatment: "Urgent surgical reattachment; time-critical to preserve vision." },
      { id: "eye_uveitis", name: "Anterior uveitis", presentation: "Painful red eye, photophobia, blurred vision, small irregular pupil; linked to HLA-B27 disease.", investigations: "Slit-lamp (cells/flare); look for systemic associations.", treatment: "Topical steroids and cycloplegics under ophthalmology; treat underlying disease." },
      { id: "eye_crao", name: "Central retinal artery occlusion", presentation: "Sudden painless monocular vision loss; pale retina with cherry-red spot, RAPD.", investigations: "Urgent assessment; investigate emboli and giant cell arteritis.", treatment: "Emergency referral; ocular massage and pressure-lowering; treat vascular cause." },
      { id: "eye_optic_neuritis", name: "Optic neuritis", presentation: "Subacute painful monocular vision loss with reduced colour vision and RAPD; MS association.", investigations: "Visual acuity, fundoscopy, MRI.", treatment: "Often recovers; steroids may speed recovery; assess for MS." },
    ],
  },
  {
    id: "infectious",
    name: "Infectious Diseases",
    icon: "🦠",
    conditions: [
      { id: "id_sepsis", name: "Sepsis", presentation: "Life-threatening organ dysfunction from infection: fever, tachycardia, hypotension, confusion.", investigations: "Sepsis screen, lactate, cultures, NEWS2.", treatment: "Sepsis Six within the hour: oxygen, cultures, IV antibiotics, fluids, lactate, urine output." },
      { id: "id_influenza", name: "Influenza", presentation: "Abrupt fever, myalgia, headache, dry cough, fatigue during winter season.", investigations: "Clinical; PCR if needed; assess complications.", treatment: "Supportive; antivirals (oseltamivir) for at-risk groups; annual vaccination." },
      { id: "id_covid", name: "COVID-19", presentation: "Fever, cough, loss of smell/taste, breathlessness; range from mild to severe.", investigations: "PCR/lateral flow, oxygen saturations, CXR if severe.", treatment: "Supportive; antivirals/steroids for at-risk or hospitalised; vaccination and isolation advice." },
      { id: "id_gastroenteritis", name: "Gastroenteritis", presentation: "Acute diarrhoea and vomiting, cramps; usually viral and self-limiting.", investigations: "Usually clinical; stool culture if blood, travel, or prolonged.", treatment: "Oral rehydration; safety-net for dehydration; hygiene and exclusion advice; antibiotics rarely needed." },
      { id: "id_hiv", name: "HIV", presentation: "Seroconversion flu-like illness; later opportunistic infections; many asymptomatic for years.", investigations: "Fourth-generation antigen/antibody test, CD4 count, viral load.", treatment: "Lifelong antiretroviral therapy; partner notification; pre-/post-exposure prophylaxis for prevention." },
      { id: "id_malaria", name: "Malaria", presentation: "Fever, rigors, headache, myalgia after travel to an endemic area; can be rapidly fatal (falciparum).", investigations: "Thick and thin blood films (three), rapid antigen test.", treatment: "Species-specific antimalarials; admit falciparum; emphasise prophylaxis and bite avoidance." },
      { id: "id_lyme", name: "Lyme disease", presentation: "Erythema migrans target rash after tick bite; later neurological, cardiac or joint features.", investigations: "Clinical for erythema migrans; serology for later disease.", treatment: "Doxycycline; longer courses for disseminated disease." },
      { id: "id_meningitis", name: "Meningitis", presentation: "Fever, headache, neck stiffness, photophobia; non-blanching rash in meningococcal sepsis.", investigations: "Blood cultures, lumbar puncture (unless contraindicated), PCR.", treatment: "Immediate IV/IM benzylpenicillin in community; ceftriaxone in hospital; notify; prophylaxis for contacts." },
      { id: "id_notifiable", name: "Notifiable diseases", presentation: "Statutory duty to report suspected cases to protect public health.", investigations: "Clinical suspicion is enough to notify; confirm with appropriate tests.", treatment: "Notify UKHSA promptly (e.g. measles, TB, meningococcal, food poisoning); arrange control measures." },
      { id: "id_abx_choice", name: "Antibiotic stewardship", presentation: "Choosing the right drug, dose and duration while minimising resistance.", investigations: "Cultures before antibiotics where possible; review local guidelines.", treatment: "Use narrowest effective agent, review at 48–72h, document indication and duration, de-escalate." },
    ],
  },
  {
    id: "haematology",
    name: "Haematology & Immunology",
    icon: "🩸",
    conditions: [
      { id: "haem_ida", name: "Iron deficiency anaemia", presentation: "Fatigue, pallor, breathlessness, koilonychia; commonest anaemia.", investigations: "FBC (microcytic), ferritin (low), blood film; investigate GI loss in at-risk groups.", treatment: "Oral iron; treat cause; refer for endoscopy if unexplained in older adults." },
      { id: "haem_b12_anaemia", name: "Pernicious anaemia", presentation: "Macrocytic anaemia with glossitis and neurological signs; autoimmune.", investigations: "B12 low, intrinsic factor antibodies, blood film (hypersegmented neutrophils).", treatment: "IM hydroxocobalamin; lifelong if pernicious; replace before folate." },
      { id: "haem_acd", name: "Anaemia of chronic disease", presentation: "Normocytic or mildly microcytic anaemia in chronic inflammation or malignancy.", investigations: "Ferritin normal/high, low transferrin saturation, raised inflammatory markers.", treatment: "Treat the underlying condition; iron only if coexisting deficiency." },
      { id: "haem_sickle", name: "Sickle cell disease", presentation: "Painful vaso-occlusive crises, anaemia, infections; autosomal recessive.", investigations: "Blood film, haemoglobin electrophoresis, newborn screening.", treatment: "Hydration, analgesia, oxygen and treat infection in crisis; hydroxycarbamide; vaccination and penicillin prophylaxis." },
      { id: "haem_thalassaemia", name: "Thalassaemia", presentation: "Microcytic anaemia disproportionate to iron status, often Mediterranean/Asian heritage.", investigations: "Blood film, electrophoresis, genetic testing.", treatment: "Monitoring for trait; transfusion and iron chelation for major disease." },
      { id: "haem_leukaemia", name: "Leukaemia", presentation: "Fatigue, infections, bruising/bleeding, bone pain; acute forms progress rapidly.", investigations: "FBC, blood film, bone marrow biopsy, cytogenetics.", treatment: "Urgent haematology referral; chemotherapy; supportive care; stem cell transplant in selected cases." },
      { id: "haem_lymphoma", name: "Lymphoma", presentation: "Painless lymphadenopathy, B symptoms (fever, night sweats, weight loss); alcohol-induced node pain in Hodgkin.", investigations: "Lymph node biopsy, CT/PET staging, LDH.", treatment: "Chemotherapy +/- radiotherapy by type and stage; specialist care." },
      { id: "haem_myeloma", name: "Multiple myeloma", presentation: "Bone pain, anaemia, renal impairment, hypercalcaemia, recurrent infection.", investigations: "Serum/urine electrophoresis, free light chains, marrow biopsy, skeletal survey (CRAB).", treatment: "Chemotherapy, bisphosphonates, supportive care; transplant in fit patients." },
      { id: "haem_itp", name: "Immune thrombocytopenia", presentation: "Bruising, petechiae, mucosal bleeding with isolated low platelets.", investigations: "FBC, blood film, exclude secondary causes.", treatment: "Observe if mild; steroids/IVIG for bleeding or very low counts; treat causes." },
      { id: "haem_anaphylaxis", name: "Anaphylaxis", presentation: "Rapid airway, breathing or circulation compromise with skin changes after an allergen.", investigations: "Clinical diagnosis; serum mast cell tryptase; later allergy testing.", treatment: "IM adrenaline, oxygen, fluids, repeat as needed; observe; adrenaline auto-injector and allergy referral." },
      { id: "haem_anticoag", name: "Anticoagulation", presentation: "Balancing thrombosis prevention against bleeding risk.", investigations: "Renal function, weight, indication, bleeding risk; INR for warfarin.", treatment: "DOAC for most AF/VTE; warfarin for mechanical valves/antiphospholipid; counsel on adherence and reversal." },
    ],
  },
  {
    id: "reproductive",
    name: "Reproductive & Sexual Health",
    icon: "⚕️",
    conditions: [
      { id: "repro_contraception", name: "Contraception", presentation: "Choosing a method by efficacy, medical eligibility and preference.", investigations: "History, BP, BMI, UKMEC eligibility; exclude pregnancy.", treatment: "LARC (implant, IUD/IUS) most effective; COCP cautions (migraine with aura, VTE risk); counsel on use." },
      { id: "repro_emergency_contra", name: "Emergency contraception", presentation: "Requested after unprotected sex or method failure.", investigations: "Timing since intercourse, cycle, medical history.", treatment: "Copper IUD most effective (up to 5 days); ulipristal or levonorgestrel; advise ongoing contraception." },
      { id: "repro_menorrhagia", name: "Heavy menstrual bleeding", presentation: "Excessive menstrual loss affecting quality of life, possible anaemia.", investigations: "FBC, pelvic exam, ultrasound; biopsy if risk factors.", treatment: "LNG-IUS first line; tranexamic/mefenamic acid; hormonal options; treat cause." },
      { id: "repro_endometriosis", name: "Endometriosis", presentation: "Cyclical pelvic pain, dysmenorrhoea, dyspareunia, subfertility.", investigations: "Pelvic exam, ultrasound; laparoscopy is definitive.", treatment: "Analgesia, hormonal suppression (COCP, progestogen); surgical excision; fertility support." },
      { id: "repro_pcos", name: "Polycystic ovary syndrome", presentation: "Irregular periods, hirsutism, acne, weight gain, subfertility.", investigations: "Rotterdam criteria; testosterone, LH/FSH, ultrasound; screen metabolic risk.", treatment: "Weight management, COCP for cycle/hirsutism, metformin; ovulation induction for fertility." },
      { id: "repro_menopause", name: "Menopause & HRT", presentation: "Vasomotor symptoms, mood and genitourinary change around 51 with amenorrhoea.", investigations: "Clinical; FSH only in selected cases.", treatment: "HRT (oestrogen plus progestogen if uterus present); vaginal oestrogen; lifestyle; discuss risks/benefits." },
      { id: "repro_ectopic", name: "Ectopic pregnancy", presentation: "Lower abdominal pain and bleeding 6–8 weeks after a missed period; shoulder tip pain if ruptured.", investigations: "Urine and serum hCG, transvaginal ultrasound.", treatment: "Expectant, methotrexate or surgery by stability and size; emergency surgery if ruptured." },
      { id: "repro_miscarriage", name: "Miscarriage", presentation: "Vaginal bleeding and pain in early pregnancy; assess viability.", investigations: "Transvaginal ultrasound, serial hCG.", treatment: "Expectant, medical (misoprostol) or surgical management; anti-D if rhesus negative; emotional support." },
      { id: "repro_antenatal", name: "Antenatal care", presentation: "Routine schedule of checks to optimise maternal and fetal health.", investigations: "Booking bloods, BP, urine, growth, screening (Down's, anomaly scan).", treatment: "Folic acid and vitamin D, lifestyle advice, vaccinations, monitor for complications." },
      { id: "repro_preeclampsia", name: "Pre-eclampsia", presentation: "New hypertension and proteinuria after 20 weeks; headache, visual change, oedema, epigastric pain.", investigations: "BP, urine PCR, bloods (FBC, LFT, U&E), fetal monitoring.", treatment: "Labetalol, monitor closely, magnesium sulfate to prevent eclampsia; delivery is definitive." },
      { id: "repro_chlamydia", name: "Chlamydia", presentation: "Often asymptomatic; discharge, dysuria, pelvic pain; commonest bacterial STI.", investigations: "Nucleic acid amplification test (vulvovaginal swab or first-void urine).", treatment: "Doxycycline; partner notification and treatment; test for other STIs; retest if indicated." },
      { id: "repro_pid", name: "Pelvic inflammatory disease", presentation: "Lower abdominal pain, deep dyspareunia, abnormal bleeding/discharge, cervical motion tenderness.", investigations: "STI screen, pregnancy test, pelvic exam.", treatment: "Low threshold for empirical antibiotics; partner treatment; counsel on fertility risk." },
      { id: "repro_breast_lump", name: "Breast lump assessment", presentation: "New lump, skin or nipple change, or pain; assess cancer risk.", investigations: "Triple assessment: examination, imaging (mammogram/ultrasound), biopsy.", treatment: "2-week-wait referral for suspicious features; manage benign causes; participate in screening." },
    ],
  },
  {
    id: "paediatrics",
    name: "Paediatrics & Child Health",
    icon: "🧒",
    conditions: [
      { id: "paeds_fever", name: "Febrile child", presentation: "Fever in a child; use traffic-light system to grade risk of serious illness.", investigations: "Assess for red flags, source; urine, bloods or septic screen as indicated.", treatment: "Antipyretics for distress, safety-net, treat source; admit amber/red features." },
      { id: "paeds_bronchiolitis", name: "Bronchiolitis", presentation: "Coryza then cough, wheeze, poor feeding and respiratory distress in infants under 1; RSV.", investigations: "Clinical; oxygen saturations; NPA if admitted.", treatment: "Supportive: feeding support and oxygen; safety-net; no routine antibiotics or steroids." },
      { id: "paeds_croup", name: "Croup", presentation: "Barking cough, stridor and hoarseness with coryza in a young child; worse at night.", investigations: "Clinical; avoid distressing the child.", treatment: "Single dose oral dexamethasone; nebulised adrenaline and admission if severe stridor." },
      { id: "paeds_asthma", name: "Childhood asthma", presentation: "Recurrent wheeze, cough and breathlessness with triggers and atopy.", investigations: "Clinical pattern; spirometry when old enough.", treatment: "Age-appropriate inhaled therapy with spacer; written action plan; treat acute attacks by severity." },
      { id: "paeds_gastroenteritis", name: "Gastroenteritis & dehydration", presentation: "Diarrhoea and vomiting with risk of dehydration in children.", investigations: "Assess hydration and red flags; stool culture if indicated.", treatment: "Oral rehydration solution, continue feeding; safety-net; IV fluids if shocked." },
      { id: "paeds_uti", name: "UTI in children", presentation: "Non-specific fever, vomiting, irritability in infants; dysuria in older children.", investigations: "Clean-catch urine for dipstick and culture; imaging by age and recurrence.", treatment: "Antibiotics per local guidance; investigate atypical or recurrent infection for renal anomalies." },
      { id: "paeds_febrile_convulsion", name: "Febrile convulsion", presentation: "Generalised seizure with fever in a child 6 months to 5 years, no CNS infection.", investigations: "Identify infection source; lumbar puncture if meningism.", treatment: "Manage fever and reassure; safety advice; simple convulsions are benign." },
      { id: "paeds_kawasaki", name: "Kawasaki disease", presentation: "Fever over 5 days with conjunctivitis, rash, lymphadenopathy, red cracked lips and extremity changes.", investigations: "Clinical criteria, inflammatory markers, echocardiogram for coronary aneurysms.", treatment: "IV immunoglobulin and aspirin; cardiology follow-up." },
      { id: "paeds_milestones", name: "Developmental milestones", presentation: "Tracking gross motor, fine motor, language and social development; flag delay or regression.", investigations: "Structured developmental assessment, hearing and vision checks.", treatment: "Early referral for delay; MDT support; reassure normal variation." },
      { id: "paeds_immunisation", name: "Immunisation schedule", presentation: "Routine childhood vaccinations to prevent serious infection.", investigations: "Check records and contraindications.", treatment: "Follow the UK schedule (6-in-1, MMR, etc.); address vaccine hesitancy; catch-up where needed." },
      { id: "paeds_nai", name: "Non-accidental injury", presentation: "Injuries inconsistent with history or development, delayed presentation, concerning interactions.", investigations: "Thorough exam, documentation, skeletal survey, senior and safeguarding involvement.", treatment: "Ensure child's safety, follow safeguarding pathway, refer to social care; share information appropriately." },
      { id: "paeds_jaundice", name: "Neonatal jaundice", presentation: "Yellow skin in a newborn; within 24h is always pathological.", investigations: "Bilirubin on treatment threshold chart, blood group/Coombs, FBC.", treatment: "Phototherapy or exchange transfusion by level and age; investigate prolonged jaundice." },
    ],
  },
  {
    id: "pharmacology",
    name: "Pharmacology & Prescribing",
    icon: "💊",
    itemNoun: "topics",
    fieldLabels: ["⚙️ Mechanism & uses", "⚠️ Adverse effects & monitoring", "💉 Prescribing & safety"],
    conditions: [
      { id: "pharm_warfarin", name: "Warfarin & DOACs", presentation: "Anticoagulants for AF and VTE; warfarin inhibits vitamin K clotting factors, DOACs are direct inhibitors.", investigations: "Warfarin needs INR monitoring; DOACs need renal function and weight; many interactions.", treatment: "DOAC first line for most; warfarin for mechanical valves/antiphospholipid; reverse with vitamin K/PCC or specific agents." },
      { id: "pharm_antibiotics", name: "Antibiotics & allergy", presentation: "Choose by likely organism, site and severity; document allergy status accurately.", investigations: "Clarify nature of penicillin allergy; cultures where possible.", treatment: "Use narrow-spectrum where possible; avoid in true anaphylaxis; review and de-escalate." },
      { id: "pharm_nsaids", name: "NSAIDs", presentation: "Anti-inflammatory analgesics inhibiting cyclo-oxygenase.", investigations: "Assess GI, renal and cardiovascular risk; check interactions.", treatment: "Lowest effective dose with PPI cover when needed; avoid in renal impairment, heart failure and with anticoagulants." },
      { id: "pharm_steroids", name: "Corticosteroids", presentation: "Potent anti-inflammatory/immunosuppressants for many conditions.", investigations: "Monitor glucose, BP, bone health and mood with prolonged use.", treatment: "Do not stop abruptly (adrenal suppression); sick-day rules; steroid card; gastric and bone protection." },
      { id: "pharm_opioids", name: "Opioids", presentation: "Strong analgesics for acute and palliative pain.", investigations: "Assess pain, function, dependence risk and renal function.", treatment: "Start low, co-prescribe laxatives, review regularly; naloxone reverses overdose; cautious in the elderly." },
      { id: "pharm_insulin", name: "Insulin", presentation: "Replaces or supplements endogenous insulin in diabetes.", investigations: "Glucose monitoring, HbA1c, hypo awareness, injection sites.", treatment: "Tailor regimen; never omit in type 1; manage hypoglycaemia; adjust in illness." },
      { id: "pharm_antihypertensives", name: "Antihypertensives", presentation: "ACE inhibitors, ARBs, calcium channel blockers and diuretics lower blood pressure.", investigations: "Check U&E after starting ACE-i/ARB; monitor BP and adherence.", treatment: "Follow stepwise pathway; avoid ACE-i/ARB combination; caution in pregnancy and renal artery stenosis." },
      { id: "pharm_lithium", name: "Lithium & narrow therapeutic index drugs", presentation: "Mood stabiliser with a narrow safety margin; toxicity risks neurological harm.", investigations: "Levels (12h post-dose), U&E, TFTs and calcium regularly.", treatment: "Maintain hydration, avoid NSAIDs/dehydration; recognise toxicity (tremor, ataxia, confusion); patient-held monitoring book." },
      { id: "pharm_pregnancy", name: "Drugs in pregnancy", presentation: "Teratogenic risk must be weighed against treating maternal illness.", investigations: "Check pregnancy status and trimester; consult resources.", treatment: "Avoid known teratogens (valproate, ACE-i, retinoids, warfarin); use safest effective option; preconception counselling." },
      { id: "pharm_paracetamol_od", name: "Paracetamol overdose", presentation: "Often asymptomatic early; later right upper quadrant pain and hepatic failure.", fields: [ { label: "☠️ Mechanism & features", value: "Toxic metabolite NAPQI depletes glutathione causing hepatocellular necrosis; early symptoms are mild." }, { label: "🔬 Investigations", value: "Paracetamol level at 4 hours post-ingestion plotted on the treatment line, LFTs, INR, U&E, venous gas." }, { label: "💉 Management", value: "N-acetylcysteine guided by the nomogram or for staggered/late presentations; refer to liver unit if criteria met." } ] },
      { id: "pharm_polypharmacy", name: "Polypharmacy in the elderly", presentation: "Multiple medicines raise interaction, adherence and falls risk.", investigations: "Structured medication review, renal function, anticholinergic burden.", treatment: "Deprescribe where appropriate, simplify regimens, align with goals and frailty." },
    ],
  },
  {
    id: "public_health",
    name: "Public Health, Ethics & Evidence",
    icon: "⚖️",
    conditions: [
      { id: "ph_capacity", name: "Consent & capacity", presentation: "Adults are presumed to have capacity; assess understanding, retention, weighing and communication.", investigations: "Capacity is decision- and time-specific; involve the patient fully.", treatment: "Act in best interests if lacking capacity; consider advance decisions and lasting power of attorney; document." },
      { id: "ph_confidentiality", name: "Confidentiality", presentation: "Duty to keep patient information private, with limited justified exceptions.", investigations: "Identify whether disclosure is required or justified in the public interest.", treatment: "Share on a need-to-know basis; breach only when required by law or to prevent serious harm; document rationale." },
      { id: "ph_safeguarding", name: "Safeguarding", presentation: "Protecting children and vulnerable adults from abuse and neglect.", investigations: "Recognise indicators; gather information; seek senior and specialist advice.", treatment: "Act on concerns, refer to safeguarding leads/social care, document; the person's safety is paramount." },
      { id: "ph_smoking", name: "Health promotion & smoking cessation", presentation: "Behaviour change opportunities at every contact (Making Every Contact Count).", investigations: "Assess readiness to change, dependence.", treatment: "Very brief advice; nicotine replacement, varenicline or bupropion; refer to cessation services." },
      { id: "ph_screening", name: "Screening programmes", presentation: "Detecting disease early in asymptomatic populations; must meet Wilson-Jungner criteria.", investigations: "Understand sensitivity, specificity and lead-time/length bias.", treatment: "UK programmes include cervical, breast, bowel, AAA and antenatal screening; counsel on benefits and limits." },
      { id: "ph_ebm", name: "Evidence-based medicine", presentation: "Integrating best evidence with clinical expertise and patient values.", investigations: "Appraise study design, bias, confounding and applicability.", treatment: "Hierarchy: systematic review/RCT above cohort/case-control; weigh effect size and confidence intervals." },
      { id: "ph_stats", name: "Diagnostic statistics", presentation: "Interpreting test performance and trial results.", investigations: "Sensitivity, specificity, predictive values, likelihood ratios, number needed to treat.", treatment: "Choose tests by purpose (rule in vs rule out); understand absolute vs relative risk; p-values and confidence intervals." },
      { id: "ph_death_cert", name: "Death certification", presentation: "Accurately recording cause of death and knowing when to refer to the coroner.", investigations: "Establish cause; identify reportable circumstances (unknown cause, violence, in custody).", treatment: "Complete the MCCD correctly; refer to coroner where required; medical examiner scrutiny." },
      { id: "ph_dvla", name: "DVLA & fitness to drive", presentation: "Many conditions affect driving safety and carry a duty to advise patients.", investigations: "Know rules for seizures, syncope, vision, diabetes and cardiac events.", treatment: "Advise the patient of their duty to inform DVLA; breach confidentiality to notify only if they continue to drive against advice." },
      { id: "ph_vaccination", name: "Vaccination & herd immunity", presentation: "Immunisation protects individuals and populations.", investigations: "Check eligibility, contraindications and informed consent.", treatment: "Promote uptake, address hesitancy with empathy, follow the national schedule." },
    ],
  },
];

// ===================================================================
// PHASES — adaptive revision plan (mapped onto the real calendar)
// ===================================================================
window.PHASES = [
  {
    id: 1, label: "Phase 1", name: "Foundation",
    weeks: "Weeks 1–7", weekStart: 1, weekEnd: 7,
    dateStart: "2026-10-19", dateEnd: "2026-12-06",
    color: "#2dd4bf", accent: "#0f3b3a",
    weekdayHrsBase: 1.5, dayOffHrsBase: 3, qsPerWeekdayBase: 25, qsPerDayOffBase: 60,
    goal: "Build broad clinical coverage across the high-yield systems and get comfortable with the Professional Dilemmas format. The aim is a first full pass of the curriculum and an honest red/amber/green rating of every system in the Tracker.",
    strategy: [
      "Work through one or two systems each week using a question bank (Passmedicine, Emedica or Pastest) by topic rather than at random.",
      "Rate each condition in the Tracker as you go — be honest, because the amber and red items drive Phase 2.",
      "Read around every question you get wrong and add the point to your notebook.",
      "Spend ten minutes a day getting familiar with the Professional Dilemmas paper: read the format and try a few scenarios in Practice mode.",
    ],
    systems: [
      { name: "Cardiovascular", priority: "HIGH", weeks: "Wks 1–2", trackerId: "cardiology" },
      { name: "Respiratory", priority: "HIGH", weeks: "Wks 1–2", trackerId: "respiratory" },
      { name: "Gastroenterology & Nutrition", priority: "HIGH", weeks: "Wks 2–3", trackerId: "gastro" },
      { name: "Endocrinology & Metabolic", priority: "HIGH", weeks: "Wks 3–4", trackerId: "endocrinology" },
      { name: "Neurology", priority: "HIGH", weeks: "Wks 4–5", trackerId: "neurology" },
      { name: "Infectious Diseases", priority: "MED", weeks: "Wks 5–6", trackerId: "infectious" },
      { name: "Haematology & Immunology", priority: "MED", weeks: "Wks 6–7", trackerId: "haematology" },
      { name: "Professional Dilemmas — familiarisation", priority: "HIGH", weeks: "Wks 1–7" },
    ],
  },
  {
    id: 2, label: "Phase 2", name: "Consolidation",
    weeks: "Weeks 8–14", weekStart: 8, weekEnd: 14,
    dateStart: "2026-12-07", dateEnd: "2027-01-24",
    color: "#38bdf8", accent: "#0c4a6e",
    weekdayHrsBase: 1.75, dayOffHrsBase: 3.5, qsPerWeekdayBase: 35, qsPerDayOffBase: 80,
    goal: "Cover the remaining systems and return to your amber and red Tracker items. Move from learning facts to answering questions accurately, and bring Professional Dilemmas into a weekly timed routine.",
    strategy: [
      "Cover the remaining systems and re-test every amber and red condition until it turns green.",
      "Mix topics within sessions so retrieval is closer to exam conditions.",
      "Do one timed Professional Dilemmas set each week and review the rationale for every response, not just the ones you got wrong.",
      "Use spaced repetition (Anki or re-rating in the Tracker) so earlier systems are not forgotten.",
    ],
    systems: [
      { name: "Renal & Urology", priority: "HIGH", weeks: "Wks 8–9", trackerId: "renal" },
      { name: "Psychiatry & Mental Health", priority: "HIGH", weeks: "Wks 8–9", trackerId: "psychiatry" },
      { name: "MSK & Rheumatology", priority: "MED", weeks: "Wks 9–10", trackerId: "rheumatology" },
      { name: "Dermatology", priority: "MED", weeks: "Wks 10–11", trackerId: "dermatology" },
      { name: "Reproductive & Sexual Health", priority: "HIGH", weeks: "Wks 11–12", trackerId: "reproductive" },
      { name: "Paediatrics & Child Health", priority: "HIGH", weeks: "Wks 12–13", trackerId: "paediatrics" },
      { name: "ENT & Ophthalmology", priority: "MED", weeks: "Wks 13–14", trackerId: "ophthalmology" },
      { name: "Professional Dilemmas — weekly timed sets", priority: "HIGH", weeks: "Wks 8–14" },
    ],
  },
  {
    id: 3, label: "Phase 3", name: "Intensification",
    weeks: "Weeks 15–19", weekStart: 15, weekEnd: 19,
    dateStart: "2027-01-25", dateEnd: "2027-02-28",
    color: "#a78bfa", accent: "#3b2a63",
    weekdayHrsBase: 2, dayOffHrsBase: 4, qsPerWeekdayBase: 45, qsPerDayOffBase: 100,
    goal: "High-volume mixed practice under time pressure. Close the last knowledge gaps in pharmacology, public health and the smaller specialties, and sit Professional Dilemmas papers to time.",
    strategy: [
      "Switch to large mixed question sets covering all systems to build speed and stamina.",
      "Target the remaining red Tracker items specifically — these are where marks are won.",
      "Sit full-length timed Professional Dilemmas papers and study the ranking logic carefully.",
      "Review pharmacology and prescribing safety, which cut across every clinical area.",
    ],
    systems: [
      { name: "Pharmacology & Prescribing", priority: "HIGH", weeks: "Wks 15–16", trackerId: "pharmacology" },
      { name: "Public Health, Ethics & Evidence", priority: "MED", weeks: "Wks 16–17", trackerId: "public_health" },
      { name: "ENT", priority: "LOW", weeks: "Wk 17", trackerId: "ent" },
      { name: "Ophthalmology", priority: "LOW", weeks: "Wk 17", trackerId: "ophthalmology" },
      { name: "Weak-area blitz (red items)", priority: "HIGH", weeks: "Wks 18–19" },
      { name: "Professional Dilemmas — full timed papers", priority: "HIGH", weeks: "Wks 15–19" },
    ],
  },
  {
    id: 4, label: "Phase 4", name: "Final Stretch",
    weeks: "Weeks 20–22", weekStart: 20, weekEnd: 22,
    dateStart: "2027-03-01", dateEnd: "2027-03-21",
    color: "#f59e0b", accent: "#5a3a0a",
    weekdayHrsBase: 2, dayOffHrsBase: 4, qsPerWeekdayBase: 50, qsPerDayOffBase: 110,
    goal: "Simulate the real exam, polish technique and protect your wellbeing. Sit full mock papers for both components, review flagged topics lightly, and rest before the day.",
    strategy: [
      "Sit at least one full Clinical Problem Solving mock and one Professional Dilemmas mock under exam timing.",
      "Review only flagged and previously red topics — resist learning new material now.",
      "Rehearse pacing: roughly a minute a question for CPS, and a clear strategy for ranking versus multiple-choice in PD.",
      "Sort logistics, sleep and the day before — arrive calm, not cramming.",
    ],
    systems: [
      { name: "Full CPS mock papers", priority: "EXAM", weeks: "Wks 20–21" },
      { name: "Full Professional Dilemmas mocks", priority: "EXAM", weeks: "Wks 20–21" },
      { name: "Targeted review of flagged topics", priority: "HIGH", weeks: "Wk 21" },
      { name: "Rest, logistics & exam day", priority: "EXAM", weeks: "Wk 22" },
    ],
  },
];

// ===================================================================
// TIPS — strategy notes for the Plan view
// ===================================================================
window.TIPS = [
  { icon: "🧭", title: "Two papers, one score", body: "The MSRA combines Clinical Problem Solving and Professional Dilemmas. Both feed your final ranking, and for many specialties the SJT paper carries real weight — so do not neglect it while drilling clinical questions." },
  { icon: "⏱️", title: "Train for the clock", body: "CPS gives you a little over a minute per question and PD is tightly timed. Practise to time from Phase 2 onwards so pace becomes automatic rather than a shock on the day." },
  { icon: "🎯", title: "Let the Tracker drive you", body: "Your amber and red ratings are a personalised syllabus. Each phase, spend most of your effort turning those items green rather than re-reading what you already know." },
  { icon: "⚖️", title: "Read PD rationale, always", body: "In Professional Dilemmas the reasoning matters more than the answer. After every scenario read why each response is appropriate or not — patient safety, honesty and seeking help recur as themes." },
  { icon: "🔁", title: "Space your repetition", body: "Re-rate systems you covered weeks ago. Spaced retrieval beats marathon re-reading, and the Tracker day-counter shows you what has gone stale." },
  { icon: "😴", title: "Protect the basics", body: "Sleep, exercise and breaks are revision tools, not luxuries. A rested brain retains more — taper intensity in the final days rather than cramming." },
];

// Default timeline. The exam date is user-chosen at onboarding (stored in
// localStorage.msra_exam_date / msra_plan_start); these are only fallbacks.
window.EXAM_DATE = "2027-01-08";   // typical mid-January MSRA window
window.PLAN_START = "2026-10-19";  // ~12 weeks out; onboarding sets the real start to today
