// ===================================================================
// MSRA PROFESSIONAL DILEMMAS — situational judgement scenarios
//   window.DILEMMAS.scenarios[]
//
//   type "rank":  options[] (usually 5). correctOrder[] lists option
//                 indices from MOST to LEAST appropriate. Scoring is by
//                 "nearness" — each response earns more the closer it is
//                 to its ideal position.
//   type "mba":   options[] (usually 8). correct[] lists the indices of
//                 the best responses; pick = how many to choose.
//
//   rationales[] is index-aligned to options[] (not to correctOrder).
//   domain is one of: integrity | pressure | empathy.
//
// Orderings follow GMC Good Medical Practice: patient safety first,
// honesty and probity, working within competence, seeking senior help,
// and treating patients and colleagues with respect.
// ===================================================================

window.DILEMMAS = {
  scenarios: [
    {
      id: "pd_int_001", type: "rank", domain: "integrity",
      stem: "You are a foundation year 1 doctor. A colleague asks you to sign a form confirming that you witnessed a procedure being carried out competently. You were not present for the procedure. Rank the following responses from most to least appropriate.",
      options: [
        "Decline to sign, explaining that you can only document what you personally witnessed.",
        "Sign the form, because you trust your colleague and want to be helpful.",
        "Offer to review the relevant findings yourself so an accurate record can be made.",
        "Sign the form but add a note stating that you did not actually witness the procedure.",
        "Say nothing and walk away from the situation.",
      ],
      correctOrder: [0, 2, 4, 3, 1],
      rationales: [
        "Records must reflect what you personally did or witnessed. Declining honestly and explaining why protects probity and patient safety — the most appropriate response.",
        "Falsely confirming you witnessed something is dishonest and could put patients at risk. This is the least appropriate option.",
        "Offering to check the relevant findings yourself is constructive: it keeps the record accurate and supports your colleague.",
        "A self-contradictory entry still risks a misleading record and does not resolve the issue honestly.",
        "Walking away avoids collusion but misses the chance to address the problem or help your colleague.",
      ],
      explanation: "Honest documentation is a core professional duty. The best responses preserve the integrity of the record while still being constructive; the worst involve signing for something you did not witness.",
    },
    {
      id: "pd_int_002", type: "rank", domain: "integrity",
      stem: "You notice that a patient has been given a double dose of a medication by another doctor. The patient appears well so far. Rank the following responses from most to least appropriate.",
      options: [
        "Assess the patient, check observations and review for any signs of harm.",
        "Say nothing, since the patient currently appears unharmed.",
        "Complete an incident report so the error can be learned from.",
        "Inform the patient about what has happened once they are safe.",
        "Quietly correct the drug chart so no one notices the mistake.",
      ],
      correctOrder: [0, 3, 2, 1, 4],
      rationales: [
        "Patient safety comes first: assessing for harm and monitoring is the immediate priority.",
        "Ignoring an error because the patient seems well risks missing later harm and breaches your duty of candour.",
        "Incident reporting supports learning and system safety; important, but it follows ensuring the patient is safe.",
        "The duty of candour means being open with the patient about an error that affects them.",
        "Concealing the error by altering records is dishonest and unsafe — the least appropriate response.",
      ],
      explanation: "The sequence is: make the patient safe, be honest with them (duty of candour), and report so others can learn. Concealment is never acceptable.",
    },
    {
      id: "pd_emp_001", type: "rank", domain: "empathy",
      stem: "A patient becomes tearful after you explain a new diagnosis of diabetes and says they feel overwhelmed. You have a busy clinic running behind. Rank the following responses from most to least appropriate.",
      options: [
        "Acknowledge their distress, pause, and give them a moment before continuing.",
        "Tell them there is nothing to worry about and move quickly to the next patient.",
        "Explore what specifically worries them and address those concerns.",
        "Offer written information and a follow-up appointment to discuss further.",
        "Continue explaining the management plan without acknowledging how they feel.",
      ],
      correctOrder: [0, 2, 3, 4, 1],
      rationales: [
        "Recognising and responding to the patient's emotion is the most appropriate first step, even when time is short.",
        "Dismissing their feelings and rushing on is the least appropriate response and damages trust.",
        "Exploring the specific worries lets you give targeted reassurance and support.",
        "Practical follow-up and written information are genuinely helpful and respect their need for time.",
        "Ploughing on with information ignores their emotional state, though it is less harmful than outright dismissal.",
      ],
      explanation: "Empathy means acknowledging emotion before information. Even in a busy clinic, a brief pause and exploration of concerns, with practical follow-up, serves the patient far better than dismissal.",
    },
    {
      id: "pd_prs_001", type: "rank", domain: "pressure",
      stem: "It is a busy night shift. A nurse asks you to urgently review a patient whose early warning score has risen, but you are midway through several other tasks. Rank the following responses from most to least appropriate.",
      options: [
        "Ask the nurse for the latest observations to gauge how urgently you must attend.",
        "Tell the nurse you are too busy and they should manage on their own.",
        "Go and assess the deteriorating patient as a priority.",
        "Call your senior for help in managing the competing demands.",
        "Finish your current paperwork first, then attend when free.",
      ],
      correctOrder: [2, 0, 3, 4, 1],
      rationales: [
        "Rapidly gathering the observations helps you triage, but the deteriorating patient should be seen promptly.",
        "Refusing to attend a deteriorating patient and offloading responsibility onto the nurse is the least appropriate and unsafe.",
        "A rising warning score signals potential deterioration; assessing the patient promptly is the priority.",
        "Escalating to a senior when demands compete is a sign of good judgement, not weakness.",
        "Delaying assessment for paperwork risks missing deterioration, though it is less unsafe than refusing outright.",
      ],
      explanation: "Under pressure, prioritise the sickest patient, use information (observations) to triage, and escalate early. Refusing to attend or putting paperwork first are the least safe choices.",
    },
    {
      id: "pd_int_003", type: "rank", domain: "integrity",
      stem: "A pharmaceutical representative offers to pay for you and your colleagues to attend an expensive social dinner, mentioning their new drug. Rank the following responses from most to least appropriate.",
      options: [
        "Politely decline, recognising the potential conflict of interest.",
        "Accept the dinner, since attending does not commit you to prescribing anything.",
        "Ask whether the event is a legitimate educational meeting and check your organisation's policy.",
        "Accept but plan to prescribe based only on the evidence.",
        "Accept and encourage your colleagues to come too.",
      ],
      correctOrder: [0, 2, 3, 4, 1],
      rationales: [
        "Declining avoids any conflict of interest and protects the trust patients place in independent prescribing.",
        "Accepting a lavish social gift is hard to justify and risks undue influence; among the least appropriate.",
        "Checking policy and the educational legitimacy of the event is a sensible, balanced step.",
        "Believing you will stay objective underestimates how gifts influence behaviour, but at least frames a check.",
        "Actively drawing colleagues into accepting the gift compounds the conflict of interest.",
      ],
      explanation: "Probity requires avoiding gifts that could be seen to influence prescribing. Declining, or at minimum checking policy and educational value, protects professional independence.",
    },
    {
      id: "pd_emp_002", type: "rank", domain: "empathy",
      stem: "An elderly patient on the ward is confused and repeatedly tries to climb out of bed, becoming distressed. Rank the following responses from most to least appropriate.",
      options: [
        "Sit with the patient, use a calm reassuring approach and try to identify a cause for the confusion.",
        "Tell the patient firmly to stay in bed and walk away.",
        "Assess for reversible causes of delirium such as infection, pain or constipation.",
        "Ask a family member or familiar staff to help reassure them if possible.",
        "Request that the patient be sedated immediately to keep them still.",
      ],
      correctOrder: [0, 2, 3, 4, 1],
      rationales: [
        "A calm, person-centred approach addresses distress and respects dignity while you look for a cause.",
        "Issuing a firm command and abandoning a distressed, confused patient is the least appropriate and unsafe.",
        "Looking for reversible causes of delirium treats the underlying problem rather than the symptom.",
        "Involving familiar people is an effective, humane way to reassure a confused patient.",
        "Sedation as a first resort risks harm and ignores the cause; it is a last resort, not a first.",
      ],
      explanation: "Confusion in an older inpatient suggests delirium. The compassionate and clinically correct approach is non-drug reassurance plus a search for reversible causes; sedation is a last resort.",
    },
    {
      id: "pd_prs_002", type: "rank", domain: "pressure",
      stem: "You are asked to perform a procedure you have only seen once and do not feel competent to do alone. The ward is busy and your senior is occupied. Rank the following responses from most to least appropriate.",
      options: [
        "Explain that you do not yet feel competent and ask for supervision.",
        "Attempt the procedure alone to avoid bothering anyone.",
        "Wait for your senior to be free and ask them to supervise or assist.",
        "Ask whether another competent colleague is available to help now.",
        "Tell the team it cannot be done and take no further action.",
      ],
      correctOrder: [0, 3, 2, 4, 1],
      rationales: [
        "Recognising the limits of your competence and asking for supervision is the safest and most professional response.",
        "Attempting an unfamiliar procedure unsupervised risks patient harm and is the least appropriate.",
        "Waiting for your senior is reasonable, though finding immediate help may be quicker if the task is urgent.",
        "Seeking another competent colleague is a good way to get the patient treated safely without delay.",
        "Declaring it undoable without seeking help leaves the patient's need unmet.",
      ],
      explanation: "You must work within your competence and seek help rather than risk patient safety. Asking for supervision or a competent colleague is far better than either attempting it alone or giving up.",
    },
    {
      id: "pd_int_004", type: "rank", domain: "integrity",
      stem: "You see a senior colleague who appears to smell of alcohol while on duty and seems unsteady. Rank the following responses from most to least appropriate.",
      options: [
        "Raise your concern discreetly and directly with the colleague.",
        "Do nothing, as they are senior to you and it is not your place.",
        "Escalate your concern to a supervising consultant or clinical lead.",
        "Ensure no patients are placed at immediate risk by their actions.",
        "Tell other junior colleagues about what you noticed.",
      ],
      correctOrder: [3, 2, 0, 1, 4],
      rationales: [
        "Speaking to the colleague may be appropriate, but ensuring patient safety and escalating take priority over an awkward direct conversation alone.",
        "Doing nothing because of hierarchy fails your duty to protect patients.",
        "Escalating to a responsible senior ensures the situation is handled properly and patients are protected.",
        "The immediate priority is making sure no patient comes to harm right now.",
        "Gossiping with peers breaches the colleague's confidentiality and does nothing to protect patients — least appropriate.",
      ],
      explanation: "Patient safety overrides hierarchy. Make patients safe, then escalate through the proper channels. Discreetly raising it with the colleague can have a place, but spreading rumours never does.",
    },
    {
      id: "pd_emp_003", type: "mba", domain: "empathy", pick: 3,
      stem: "A patient who does not speak English well has come for the results of investigations. You need to explain a significant new diagnosis. Select the THREE most appropriate actions.",
      options: [
        "Arrange a professional interpreter before discussing the results.",
        "Use the patient's young child to translate the diagnosis.",
        "Check the patient's understanding using teach-back through the interpreter.",
        "Rush the explanation because the clinic is busy.",
        "Give the patient written information in their own language if available.",
        "Speak louder in English so they understand better.",
        "Proceed without an interpreter to save time.",
        "Assume they understand if they nod along.",
      ],
      correct: [0, 2, 4],
      rationales: [
        "A professional interpreter is essential for accurate, confidential communication of a significant diagnosis.",
        "Using a child to translate is inappropriate: it breaches confidentiality and places an unfair burden on the child.",
        "Checking understanding (teach-back) confirms the message was received correctly.",
        "Rushing undermines understanding and compassion.",
        "Written information in the patient's language reinforces the discussion and aids recall.",
        "Speaking louder does not overcome a language barrier and can feel disrespectful.",
        "Proceeding without an interpreter risks serious misunderstanding.",
        "Assuming understanding from nodding is unsafe and presumptuous.",
      ],
      explanation: "Good communication across a language barrier needs a professional interpreter, a check of understanding, and reinforcement with translated written material — never family members (especially children) or assumptions.",
    },
    {
      id: "pd_prs_003", type: "mba", domain: "pressure", pick: 3,
      stem: "You are running 45 minutes behind in clinic and feel stressed and rushed. Several patients are waiting. Select the THREE most appropriate actions.",
      options: [
        "Maintain safe, thorough care for the patient in front of you.",
        "Ask reception to update and apologise to waiting patients.",
        "Cut corners on examinations to catch up quickly.",
        "Ask a colleague or senior whether they can help see some patients.",
        "Vent your frustration to the next patient.",
        "Stop documenting to save time.",
        "Skip checking results because you are behind.",
        "Refuse to see any more patients today.",
      ],
      correct: [0, 1, 3],
      rationales: [
        "Safe, thorough care must not be sacrificed for speed — the patient in front of you deserves your full attention.",
        "Keeping waiting patients informed is respectful and reduces frustration.",
        "Cutting corners on examination risks missing important findings.",
        "Asking for help to share the load is sensible and protects safety.",
        "Venting at a patient is unprofessional and unfair.",
        "Documentation is part of safe care and a medico-legal necessity.",
        "Skipping results checks risks missing significant findings.",
        "Refusing to see waiting patients abandons your responsibility.",
      ],
      explanation: "Under time pressure, protect the quality and safety of care, communicate honestly with those waiting, and seek help — rather than cutting clinical corners or taking frustration out on patients.",
    },
    {
      id: "pd_int_005", type: "mba", domain: "integrity", pick: 3,
      stem: "A friend who is not your patient asks you to prescribe antibiotics for their sore throat over text, without an assessment. Select the THREE most appropriate actions.",
      options: [
        "Explain that you cannot prescribe without a proper assessment.",
        "Advise them to see their own GP or an appropriate service.",
        "Prescribe the antibiotics to save them the trouble.",
        "Offer safety-netting advice on when to seek medical help.",
        "Backdate a prescription to make it look routine.",
        "Ask another colleague to prescribe instead without assessing.",
        "Tell them antibiotics are always needed for a sore throat.",
        "Ignore the message completely without explanation.",
      ],
      correct: [0, 1, 3],
      rationales: [
        "Prescribing without an assessment is unsafe and outside good practice; explaining this is honest and appropriate.",
        "Directing them to their own GP or an appropriate service ensures they get proper care.",
        "Prescribing without assessment risks harm and breaches prescribing standards.",
        "General safety-netting advice is a reasonable, caring thing to offer.",
        "Falsifying a prescription is dishonest and unlawful.",
        "Asking a colleague to prescribe without assessment simply outsources the same unsafe act.",
        "Most sore throats are viral; claiming antibiotics are always needed is incorrect.",
        "Ignoring a friend without explanation is neither kind nor helpful.",
      ],
      explanation: "You should not prescribe for friends or family except in emergencies. The right approach is to explain why, signpost to proper care, and offer general safety advice — never to prescribe without assessment or falsify records.",
    },
    {
      id: "pd_emp_004", type: "mba", domain: "empathy", pick: 3,
      stem: "A patient is angry and raises their voice because they have waited a long time and feel ignored. Select the THREE most appropriate actions.",
      options: [
        "Listen calmly and acknowledge their frustration.",
        "Apologise for the wait and explain what you can do now.",
        "Raise your own voice to assert control.",
        "Threaten to refuse to see them if they do not calm down.",
        "Try to understand and address the underlying concern.",
        "Walk away and leave them without explanation.",
        "Tell them their anger is unjustified.",
        "Document nothing about the interaction.",
      ],
      correct: [0, 1, 4],
      rationales: [
        "Calm, active listening de-escalates anger and shows respect.",
        "A genuine apology and a clear plan address the cause of the frustration.",
        "Matching their volume escalates conflict.",
        "Threats damage trust and inflame the situation (unless there is a genuine safety issue requiring boundaries).",
        "Addressing the underlying concern resolves the real problem.",
        "Abandoning the patient without explanation worsens the situation.",
        "Telling them their feelings are unjustified is dismissive.",
        "Not documenting a significant interaction is poor practice.",
      ],
      explanation: "De-escalation relies on calm listening, a sincere apology, and addressing the real concern. Confrontation, threats and dismissal all make things worse.",
    },
    {
      id: "pd_prs_004", type: "rank", domain: "pressure",
      stem: "You realise you have made a mistake in calculating a drug dose, but you are about to hand over and go home after a long shift. The patient has not yet received the dose. Rank the following responses from most to least appropriate.",
      options: [
        "Correct the prescription immediately before the dose is given.",
        "Leave it for the next shift to notice and fix.",
        "Tell the nurse about to administer the dose so it is not given incorrectly.",
        "Hand over the error clearly to the incoming team.",
        "Say nothing because the dose has not been given yet.",
      ],
      correctOrder: [0, 2, 3, 1, 4],
      rationales: [
        "Fixing the prescription before any harm can occur is the immediate priority.",
        "Hoping the next shift catches it gambles with patient safety.",
        "Directly alerting the person about to give the drug prevents the error reaching the patient.",
        "A clear handover ensures continuity and that the correction is understood, though acting now is better than deferring.",
        "Staying silent because no harm has happened yet ignores your duty and risks the error proceeding — least appropriate.",
      ],
      explanation: "Tiredness and handover pressure do not lessen your responsibility. Act immediately to prevent the error reaching the patient, alert the administering nurse, and hand over clearly. Silence is never acceptable.",
    },
  ],
};
